############################################################
#
# 配置数据源相关	使用阿里巴巴的 druid 数据源
# redis 配置
#Redis数据库索引(默认为0)
############################################################
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/imooc-video-dev
    username: root
    password: 073018
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      stat-view-servlet:
        allow: true
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    pool:
      max-active: 1000



      max-wait: -1
      max-idle: 10
      min-idle: 2
    timeout: 0
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
############################################################
#
# mybatis 配置
############################################################
mybatis:
  type-aliases-package: com.imooc.pojo
  mapper-locations: classpath:mapper/*.xml
# 通用 Mapper 配置
mapper:
  mappers: com.imooc.utils.MyMapper
  not-empty: false
  identity: MYSQL
# 分页插件配置
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
  params: count=countSql

# 配置api端口号
server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8


